all : demonstration

demonstration :
		pdflatex decompositionVariance.tex>/dev/null  && pdflatex decompositionVariance.tex>/dev/null  

clean :
	rm -f ./*.aux
	rm -f ./*.log
	rm -f ./*.out
	rm -f ./*.pdf
	rm -f ./*.synctex.gz
	rm -f ./*.toc
